//
//  LoginInteractor.swift
//  Netec_2023
//
//  Created Administrator on 21/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginInteractor {
    //MARK: - Protocol Properties
    weak var presenter: LoginPresenterProtocol?
}

//MARK: - Interactor Methods
extension LoginInteractor: LoginInteractorProtocol {
    
}
