//
//  LoginPresenter.swift
//  Netec_2023
//
//  Created Administrator on 21/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter {
    //MARK: - Protocol Properties
    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol

    //MARK: - Life Cycle
    init(interface: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension LoginPresenter: LoginPresenterProtocol {
    func login() {
        router.login()
    }
    
    func register() {
        router.register()
    }
    
    func password() {
        router.password()
    }
    
    
}

//MARK: - Private functions
extension LoginPresenter {
    
}
