//
//  LoginRouter.swift
//  Netec_2023
//
//  Created Administrator on 21/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController(nibName: nil, bundle: nil)
        let interactor = LoginInteractor()
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

//MARK: - Router Metods
extension LoginRouter: LoginWireframeProtocol {
    func login() {
       print("logeado")
    }
    
    func register() {
        let vc = RegistroRouter.createModule()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func password() {
        let vc = RecuperacionPasswordRouter.createModule()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    
}

//MARK: - Private functions
extension LoginRouter {
    
}
