//
//  LoginProtocols.swift
//  Netec_2023
//
//  Created Administrator on 21/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginWireframeProtocol: AnyObject {
    func login()
    func register()
    func password()
}
//MARK: Presenter -
protocol LoginPresenterProtocol: AnyObject {
    func login()
    func register()
    func password()
}

//MARK: Interactor -
protocol LoginInteractorProtocol: AnyObject {

  var presenter: LoginPresenterProtocol?  { get set }
}

//MARK: View -
protocol LoginViewProtocol: AnyObject {

  var presenter: LoginPresenterProtocol?  { get set }
}
