//
//  RegistroPresenter.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegistroPresenter {
    //MARK: - Protocol Properties
    weak private var view: RegistroViewProtocol?
    var interactor: RegistroInteractorProtocol?
    private let router: RegistroWireframeProtocol

    //MARK: - Life Cycle
    init(interface: RegistroViewProtocol, interactor: RegistroInteractorProtocol?, router: RegistroWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension RegistroPresenter: RegistroPresenterProtocol {
    
}

//MARK: - Private functions
extension RegistroPresenter {
    
}
