//
//  ContactosViewController.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ContactosViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: ContactosPresenterProtocol?

    //MARK: - Properties
    private var tableViewContactos: UITableView = {
        let tableView = UITableView()
        tableView.translatesAutoresizingMaskIntoConstraints = false
        tableView.register(TableViewCell.self, forCellReuseIdentifier: "TableViewCell")
        return tableView
    }()
    
    //MARK: - Life Cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        configUI()
    }
    
    //MARK: - Methods
    func configUI(){
        tableViewContactos.delegate = self
        tableViewContactos.dataSource = self
        view.addSubview(tableViewContactos)
        NSLayoutConstraint.activate([
            tableViewContactos.topAnchor.constraint(equalTo: view.topAnchor),
            tableViewContactos.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            tableViewContactos.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            tableViewContactos.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
        
    }
}

//MARK: - View Methods
extension ContactosViewController: ContactosViewProtocol, UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let celda = tableViewContactos.dequeueReusableCell(withIdentifier: "TableViewCell", for: indexPath) as! TableViewCell
//        let model = [indexPath.row]
//        celda.configure([indexPath.row])
        return celda
    }
    
    
}

//MARK: - Private functions
extension ContactosViewController {
    
}
