//
//  ContactosInteractor.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ContactosInteractor {
    //MARK: - Protocol Properties
    weak var presenter: ContactosPresenterProtocol?
}

//MARK: - Interactor Methods
extension ContactosInteractor: ContactosInteractorProtocol {
    
}
