//
//  ContactosProtocols.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ContactosWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol ContactosPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol ContactosInteractorProtocol: AnyObject {

  var presenter: ContactosPresenterProtocol?  { get set }
}

//MARK: View -
protocol ContactosViewProtocol: AnyObject {

  var presenter: ContactosPresenterProtocol?  { get set }
}
