//
//  RecuperacionPasswordProtocols.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RecuperacionPasswordWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol RecuperacionPasswordPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol RecuperacionPasswordInteractorProtocol: AnyObject {

  var presenter: RecuperacionPasswordPresenterProtocol?  { get set }
}

//MARK: View -
protocol RecuperacionPasswordViewProtocol: AnyObject {

  var presenter: RecuperacionPasswordPresenterProtocol?  { get set }
}
