//
//  RecuperacionPasswordPresenter.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecuperacionPasswordPresenter {
    //MARK: - Protocol Properties
    weak private var view: RecuperacionPasswordViewProtocol?
    var interactor: RecuperacionPasswordInteractorProtocol?
    private let router: RecuperacionPasswordWireframeProtocol

    //MARK: - Life Cycle
    init(interface: RecuperacionPasswordViewProtocol, interactor: RecuperacionPasswordInteractorProtocol?, router: RecuperacionPasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension RecuperacionPasswordPresenter: RecuperacionPasswordPresenterProtocol {
    
}

//MARK: - Private functions
extension RecuperacionPasswordPresenter {
    
}
