//
//  RecuperacionPasswordInteractor.swift
//  Netec_2023
//
//  Created Administrator on 22/06/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecuperacionPasswordInteractor {
    //MARK: - Protocol Properties
    weak var presenter: RecuperacionPasswordPresenterProtocol?
}

//MARK: - Interactor Methods
extension RecuperacionPasswordInteractor: RecuperacionPasswordInteractorProtocol {
    
}
